[soyeon] Section02 001~006 문제 해결
9FEM/Weekly_Algorithm pull request #15
Opened 2023-04-11 05:52 UTC by sy412

알고리즘을 혼자 생각해내기 어려웠고, 특히 대각선 합을 찾는 부분과 봉우리 문제가 어려웠습니다. 7번문제는 이해하지 못하여 더 고민해보겠습니다,,!

2023-04-11 06:30 UTC, ChoByungHyun commented on section02/soyeon/006.js
해당 로직은 row랑 col의 최대값을 뽑아내지 않고 계속 초기화만 시켜주면서 돌고 있기 때문에 row, col은 마지막 행, 열 값으로 대각선과 비교 중입니다 !
첫 for문에서 최대값만 뽑아주면 될거같습니당

2023-04-11 06:59 UTC, ChoByungHyun commented on section02/soyeon/005.js
2번째 for문에서 j를 0부터 시작하도록 해야 모든 점수를 비교하기 때문에 정상적으로 출력이 됩니다?

2023-04-11 07:18 UTC, ChoByungHyun commented on section02/soyeon/002.js
그냥 앞 뒤 학생을 비교하고 있기 때문에 앞에 큰 친구가 온다고 가정하면 오류가 발생합니다!

그래서 저는 앞에서 컸던 친구를 따로 관리해서 그 친구와 비교했습니당

2023-04-11 08:02 UTC, ChoByungHyun approved these changes
고생하셨습니다. 잘 봤습니다!

2023-04-11 08:32 UTC, d-charlie-kim requested changes
수고하셨습니다.

2, 5, 6번에서 자잘한 실수만 수정하시면 좋을 것 같습니다!

2023-04-11 08:32 UTC, d-charlie-kim commented on section02/soyeon/002.js
문제를 잘못 이해하신게 아닌가 싶습니다.

반례:
const arr = [50, 10, 11, 12, 13, 14, 15, 16];
yours: 6
answer: 1

2023-04-11 08:32 UTC, d-charlie-kim commented on section02/soyeon/006.js
동의합니다

2023-04-11 08:32 UTC, d-charlie-kim commented on section02/soyeon/005.js
문제에서 `N(학생 수)`가 주어지기 때문에
17번 줄에서 `answer`를 `[1, 1, 1, 1, 1]`로 `5칸` 만큼 정적 할당 하시면 안됩니다.
`N`에 따라서 `동적 할당`을 해주셔야 합니다.

 `const answer = new Array('arrayLength')` 이렇게 넣어주시면 해당 변수에 맡게 동적 할당 됩니다.
 https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/Array
 
 이 MDN 부분 참고하시면 좋을 것 같습니다.

2023-04-11 08:50 UTC, haron-lee approved these changes
고생하셨습니다 소연넴!
어려우신데도 풀려고 열심히 하는 모습이 인상 깊었습니다.
저도 아직 멀었지만 비슷한 레벨의 문제를 많이 접해보시면은 조금 더 실력향상이 되실 것 같아요! 이 문제들 말고도 비슷한 레벨의 문제들을 접해보시기를 추천드립니다!

2023-04-11 11:18 UTC, Da-Youn approved these changes
소연님! 코드 잘 봤습니다 :-) 수고하셨어요~!

2023-04-13 08:48 UTC, sypaik-dev approved these changes
수고하셨습니다 소연님~~! 코드가 깔끔해서 좋네요,,

2023-04-13 08:50 UTC, d-charlie-kim approved these changes

2023-04-13 14:19 UTC, doong2imdang approved these changes
소연님 같이 으쌰으쌰해보자구여~ 잘봤습니당ㅎㅎ 수고하셨어요!!

2023-04-15 07:54 UTC, merged