[sypaik] Section01: 001 ~ 017 문제 해결
9FEM/Weekly_Algorithm pull request #7
Opened 2023-04-03 08:07 UTC by sypaik-dev

일곱난쟁이 08번 푸는 데에 메소드가 생각나지 않았습니다.

`reduce( )` - 배열을 순차적으로 순회하면서 배열의 값을 누적
`indexOf( )` - 일치하는 데이터의 첫번째 index  반환 ==> 필터링 해주어 중복 제거
중첩 for문을 이용

[추가] 직접 입력값을 넣어 테스트해볼 수 있어 좋았습니다.

2023-04-03 10:55 UTC, d-charlie-kim reviewed
수고하셨습니다!
반례가 있는 문제가 몇개 있었습니다.

16, 17번 indexOf로 처리하는 방식이 기억에 남습니다.

2023-04-03 10:55 UTC, d-charlie-kim commented on section01/sypaik/001.js
조건문 if else if 문으로 a b c 비교를 모두 하고 있습니다.
for 반복문이 필요가 없어보입니다!
(3번 반복하시려고 하셨다면, 종료 조건이 `i < 3` 이 되어야 합니다)

2023-04-03 10:55 UTC, d-charlie-kim commented on section01/sypaik/005.js
조건문 비교대상이 잘못되었습니다.

반례
1. `[1, 2, 3, 4, 5, 6, 7]` 
--> `return 0  //  expected 1`
(min 초기값 0이 return 됩니다.)

2. `[-100, -50, 5, 4, 3, 2, 1]`
--> `return 1  //  expected -100`
(현재 min값과 별개로 현재 인덱스 값과 뒤 인덱스 값만 비교해서 min에 덮어씌워버립니다.)

2023-04-03 10:55 UTC, d-charlie-kim commented on section01/sypaik/008.js
`if 조건문` 내에 `for 반복문` 종료 코드가 있어야 합니다.
--> 조건에 맞는 상황을 찾고도, 계속 반복해서 찾습니다.

반례
```
const testB = [20, 20, 20, 20, 20, 10, 10, 10, 10];
console.log(solution(testB));

// return [20, 10, 10, 10, 10]
// expected [20, 20, 20, 10, 10, 10, 10]
```

2023-04-03 10:55 UTC, d-charlie-kim commented on section01/sypaik/012.js
`String.prototype.toUpperCase()` 는 대문자로 변환된 새로운 문자열을 반환합니다.
--> 문자열 전체가 바뀌기 때문에 `for 반복문`이 없어도 괜찮습니다.

2023-04-03 11:54 UTC, haron-lee commented on section01/sypaik/006.js
문제를 푸는 것에는 이상이 없지만, 7개의 자연수가 아닌 7개 이상 혹은 그보다 작은 자연수가 입력되었을 때에도 대응 할 수 있도록 for문 안의 `i < 7` 보다는 `i < numbers.length` 가 되는 게 좋을 것 같습니다!

2023-04-03 12:01 UTC, haron-lee approved these changes
### 인상 깊은 점
1. 2번 문제 저는 단순 조건문만 작성했는데 `Math.max()`를 사용한 것이 인상 깊었습니다! 
2. 16번, 17번 문제 저와 다르게 `indexOf()`를 사용하여 중복을 제거한 한 문자열을 출력한 것이 인상깊었습니다!

2023-04-03 15:37 UTC, d-charlie-kim requested changes
수고하셨습니다!
반례가 있는 문제가 몇개 있었습니다.

16, 17번 indexOf로 처리하는 방식이 기억에 남습니다.

2023-04-04 07:47 UTC, ChoByungHyun commented on section01/sypaik/002.js
max로 뽑아내고 계산하니 깔끔하네요

2023-04-04 08:11 UTC, ChoByungHyun approved these changes
고생하셨습니다. 잘봤습니당.
2번 문제 max로 뽑아내고 계산하신게 인상깊었습니다.

2023-04-04 08:21 UTC, d-charlie-kim approved these changes
확인했습니다.

2023-04-06 01:14 UTC, Da-Youn approved these changes
수고하셨습니다~~~!

2023-04-06 09:20 UTC, merged