[pig] Section01: 001 ~ 017 문제해결
9FEM/Weekly_Algorithm pull request #8
Opened 2023-04-03 12:29 UTC by ChoByungHyun

백수연님 문제가 어려웠습니다.

push, toUpperCase, slice, split 등 메서드들을 잘 몰랐는데 그래도 금방 이해했지만 reduce 같은 경우 좀 어지러웠습니다.

2023-04-03 15:34 UTC, d-charlie-kim requested changes
수고하셨습니다.
`return`이 일찍 들어간 12번 문제 확인이 필요합니다.

코드를 읽을때 `i`를 `index`, `숫자`라고 인식하는 경우가 많습니다.
그래서 `for (let i of str)` 에서 `i` 보다는 다른 문자를 사용하는 것을 추천드립니다.

indexOf 활용과 substring 활용이 기억에 남습니다.

2023-04-03 15:34 UTC, d-charlie-kim commented on section01/pig/012.js
return 과 console.log 줄 위치가 바뀐 것 같습니다.

2023-04-04 00:42 UTC, ChoByungHyun commented
> 



> 수고하셨습니다. `return`이 일찍 들어간 12번 문제 확인이 필요합니다.
> 
> 코드를 읽을때 `i`를 `index`, `숫자`라고 인식하는 경우가 많습니다. 그래서 `for (let i of str)` 에서 `i` 보다는 다른 문자를 사용하는 것을 추천드립니다.
> 
> indexOf 활용과 substring 활용이 기억에 남습니다.

2023-04-04 00:44 UTC, ChoByungHyun commented
> 수고하셨습니다. `return`이 일찍 들어간 12번 문제 확인이 필요합니다.
> 읽으시느라 고생하셨습니다. 감사합니다.
 
> 코드를 읽을때 `i`를 `index`, `숫자`라고 인식하는 경우가 많습니다. 그래서 `for (let i of str)` 에서 `i` 보다는 다른 문자를 사용하는 것을 추천드립니다.
> 그게 좋을 것 같네요 ! 감사합니당

> indexOf 활용과 substring 활용이 기억에 남습니다.

2023-04-04 07:24 UTC, d-charlie-kim commented on section01/pig/012.js
죄송합니다!

2023-04-04 07:26 UTC, d-charlie-kim approved these changes
확인했습니다.

2023-04-04 07:26 UTC, ChoByungHyun reviewed
굿

2023-04-04 07:26 UTC, ChoByungHyun commented on section01/pig/012.js
어 한줄에 들어가있지않나요?
return console.log(str.toUpperCase());

2023-04-04 07:39 UTC, haron-lee commented on section01/pig/005.js
예제를 배열로 넣으면 더 편하실 것 같습니다!

2023-04-04 07:41 UTC, sypaik-dev approved these changes
코드 잘봤습니다! 수고하셨습니다~~

2023-04-04 07:41 UTC, sypaik-dev commented on section01/pig/014.js
sort( )를 이용하여 내림차순으로 정렬하여 구하신 부분이 인상적이였습니다. sort와 더 친해져야겠습니다

2023-04-04 07:43 UTC, haron-lee reviewed
고생하셨습니다! 

14번 문제 `sort()`로 내림차순 하여 푼 게 기억에 남습니다!

2023-04-04 07:43 UTC, haron-lee approved these changes
고생하셨습니다!

14번 문제 sort()로 내림차순 하여 푼 게 기억에 남습니다!

2023-04-04 07:45 UTC, ChoByungHyun commented on section01/pig/005.js
인죵

2023-04-06 01:23 UTC, Da-Youn approved these changes
코드 잘 보았습니다. 수고하셨어요!

2023-04-06 11:23 UTC, merged